### ISSUE TITLE
navbar css

### ISSUE THREAD

**Issue by Helias** [azerothcore/azerothcore.github.io#102]
![image](https://user-images.githubusercontent.com/519778/211208343-6bfc9483-b015-4c89-9a58-926a5ca7527b.png)

**Comment by IntelligentQuantum** [comment]
If I have time, I will rewrite both the main site and the document with Next.JS

If you agree

**Comment by Helias** [comment]
not sure if it is worth to work on it
would be better to create documentation on acore-api repository, because several people are not able to use it

**Comment by Helias** [comment]
You could continue this https://github.com/azerothcore/azerothcore.org-website
this is a rewrite of the same website, it should be almost done but the dev abbandoned the project :(
it's in reactjs so it should be compliant to what you want to do

**Comment by IntelligentQuantum** [comment]
Ok tnx, i will working on it, in my free time
