### ISSUE TITLE
Allow catalogue to display  > 8 modules at a time

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/azerothcore.github.io#141]

**Comment by Helias** [comment]
how much? you only need to change this line https://github.com/azerothcore/azerothcore.github.io/blob/master/assets/default.json#L4C17-L4C17
we could let the user customize it using the catalogue but for now it's a config written in that file

**Comment by Kitzunu** [comment]
Ah was trying to find that.

I was thinking 8 was kind of odd, so we could default to 10. But let the user choose between 10, 25, 50, 100 maybe?

**Comment by Helias** [comment]
we could set 10 for now and make a feature to make it dynamic and let the user to choose it
