### ISSUE TITLE
Module catalogue hitting github rate limit

### ISSUE THREAD

**Issue by Rochet2** [azerothcore/azerothcore.github.io#56]
Opening chrome dev tools and navigating to https://www.azerothcore.org/catalogue.html multiple times or doing searches in the catalogue or swapping pages in pagination will get the menus stuck because github returns 403 due to rate limits of unauthenticated user.

[example image](https://user-images.githubusercontent.com/468816/137811924-4e618790-d1e8-4ea0-ac3e-faaffaeed3e1.png)

The limits are
10/minute for searching https://docs.github.com/en/rest/reference/search#rate-limit
60/hour for otherwise https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting

A single page view or search spends 4 calls to the API, so one can only search 2 times before getting stuck for a minute
and some 15 page views (or searches?) to get stuck for an hour.

Some solution suggestions:
- [ ] Improve handling of hitting a rate limit, as currently user sees a never ending search spinner
- [ ] Do not do 4 requests on every search (or page view), but rather limit it to 1, which lessens the amount of times one hits the rate limit
- [ ] Client side cache (localstorage) that is evicted based on time (2h?) to avoid duplicate searches from spending the rate
- [ ] Fetching more data at a time, making there to be less need to swap pages in pagination. (per_page = 100)
- [ ] Doing searches in-browser rather than through github API, however, this seems to be slightly difficult as github API [restricts per_page to 100](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#pagination), so all data cannot possibly be fetched in future from github at once.

Maybe someone wants something to do for hacktoberfest? :)

**Comment by Helias** [comment]
The block is for IP, so 10 people with different IPs and different client-side cache should be ok, but even a back-end solution could be a good one
